### ISSUE TITLE
Where the apk is downloadable securely ?

### ISSUE THREAD

**Issue by Pr0gmaT1k** [6rus/sms2mail#3]
Where the apk is downloadable securely ?
:)

**Comment by 6rus** [comment]
Was on Playstore... But has been removed.
I don't have much time to look on that project right now...

**Comment by xmokur** [comment]
I need apk pls

**Comment by Pr0gmaT1k** [comment]
This freenium app work fine:
https://play.google.com/store/apps/details?id=com.gawk.smsforwarder&hl=en_CA&gl=US
